### ISSUE TITLE
Add option to install particular fonts

### ISSUE THREAD

**Issue by ronaldtse** [fontist/setup-fontist#4]
Right now the user needs to specify additional lines to install fonts, as in:
```yaml
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fontist/setup@v1
      - run: fontist install "Fira Code"
```

It would be much better if we can specify the fonts to install directly:
```yaml
      - uses: fontist/setup@v1
        with:
          fonts: Fira Code
```

GitHub Actions arguments only support `string | number | boolean` so we can't use an array, but multiple fonts can be specified using semicolons or commas (since ?

```yaml
      - uses: fontist/setup@v1
        with:
          fonts: Fira Code, Inter
```

**Comment by jcbhmr** [comment]
> GitHub Actions arguments only support string | number | boolean so we can't use an array, but multiple fonts can be specified using semicolons or commas (since ?

I suggest multiline strings if you do in fact do this:

```yml
      - uses: fontist/setup@v1
        with:
          fonts: Fira Code
```

```yml
      - uses: fontist/setup@v1
        with:
          fonts: |
            Fira Code
            Inter
```

There's even a core method for it: `core.getMultilineInput("input-name-here")` https://www.npmjs.com/package/@actions/core

Examples from actions/cache and actions/upload-artifact:

```yml
    - name: Save Primes
      id: cache-primes-save
      uses: actions/cache/save@v4
      with:
        path: |
          path/to/dependencies
          some/other/dependencies
        key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}
```

```yml
- uses: actions/upload-artifact@v4
  with:
    name: my-artifact
    path: |
      path/output/bin/
      path/output/test-results
      !path/**/*.tmp
```

**Comment by jcbhmr** [comment]
I would be _cautious_ about this. I haven't seen any other setup-$THING action install packages or things on-the-spot when setting up. So I don't know if they don't do it for a reason or something or what.

setup-node, setup-python, setup-ruby, etc. seem to always leave package installation (even global package installation) to either a package.json requirements.txt or Cargo.toml or whatever OR they rely on _you_ to `package-manager install --global $THING` in your script. 🤷‍♂️ Just a thought. It'd also be shorter lol

```yml
# 3x lines
- uses: fontist/setup@v1
  with:
    fonts: Fira Code
```
vs
```yml
# 2x lines
- uses: fontist/setup@v1
- run: fontist install "Fira Code" 
```

also you could shorten it even more if `fontist install` supported a variable number of arguments like `cargo add` does or `npm install` does or `pip install` does.  🤷‍♂️

```yml
# 2x lines
- uses: fontist/setup@v1
- run: fontist install "Fira Code" "Inter" "Open Sans" "Consolas" "Arial" "Times New Roman"
```
vs
```yml
# lots of lines 🤷‍♂️
- uses: fontist/setup@v1
  with:
    fonts: |
      Fira Code
      Inter
      Open Sans
      Consolas
      Arial
      Times New Roman
```

**Comment by ronaldtse** [comment]
[`setup-ruby`](https://github.com/ruby/setup-ruby) does allow installing of gems through the `Gemfile` using bundler:
```yaml
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
```

We could use `manifest.yaml` for the same purpose, which is already defined here:
https://github.com/fontist/setup-fontist/blob/5922aae3bf37f2c1ab7f55390d8b94d74fc16565/action.yml#L18-L20

What about something like this:

```yaml
- uses: fontist/setup@v1
  with:
    manifest: true # The manifest is at manifest.y{a,}ml
```

As a side node, perhaps `fontist.y{a,}ml` would work better than `manifest.y{a,}ml`?
