### ISSUE TITLE
Isolate Ruby installation from system ruby version

### ISSUE THREAD

**Issue by jcbhmr** [fontist/setup-fontist#5]
_Ideally_ the fontist installation is self contained such that this:

```yml
- uses: ruby/setup-ruby@v1
  with:
    ruby-version: "ruby-3.0.0"
- uses: fontist/setup@v1
- run: ruby --version
```

would return the "ruby-3.0.0" version INSTEAD OF the version that "fontist/setup" installed globallyfor itself to use. That means somehow shoving Ruby and the fontist cli ruby files somewhere out of the main system path.

note that Ruby needs to know the dest path ahead of time (its somehow hardcoded in the binaries/config)

_thoeretically_ this could be done with something like this:

```sh
curl -fsSL https://github.com/ruby/setup-ruby/releases/... idk some URL to download the .zip release archive
unzip setup-ruby-v1.2.3
export RUNNER_TOOL_CACHE=/my/custom/path
export GITHUB_PATH=/github-path.txt
export GITHUB_ENV=/github-env.txt
node setup-ruby-v1.2.3/dist/index.js

/my/custom/path/gem install fontist

# then somehow cache the /my/custom/path or whatever
```
maybe?
