### ISSUE TITLE
Support semver specifiers in `fontist-version` field

### ISSUE THREAD

**Issue by jcbhmr** [fontist/setup-fontist#9]
make this work:

```yml
- uses: fontist/setup-fontist@v1
  with:
    # examples
    fontist-version: "1"
    fontist-version: "1.x"
    fontist-version: "^1.0.0"
    fontist-version: latest
```
